#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

function logStep() {
  echo -e "\n\e[1;32m$1\e[0m"
}

logStep "Processo de instalacao"

logStep "Instalando dependencias"
sudo apt -y install wget git ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen lua5.4
sudo DEBIAN_FRONTEND=noninteractive apt install -y composer

if [[ -e "/usr/local/share/nvim/site/pack/packer/start/packer.nvim" ]]; then
  logStep "Packer.nvim já está instalado"
else
  logStep "Clonando packer.nvim"
  git clone --depth 1 https://github.com/wbthomason/packer.nvim /usr/local/share/nvim/site/pack/packer/start/packer.nvim
fi

cd
logStep "Instalando NeoVim"
if [[ -e "neovim" ]]; then
  git pull
else
  git clone https://github.com/neovim/neovim
fi
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
cd

logStep "Instalando RipGrep"
RIPGREP_VERSION=$(curl -s "https://api.github.com/repos/BurntSushi/ripgrep/releases/latest" | grep -Po '"tag_name": "\K[0-9.]+')
#wget -O ripgrep.deb "https://github.com/BurntSushi/ripgrep/releases/download/${RIPGREP_VERSION}/ripgrep_${RIPGREP_VERSION}_amd64.deb"
wget -O ripgrep.deb "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb"
sudo dpkg -i ./ripgrep.deb
rm -rf ripgrep.deb

# Verifica se a pasta para fonts já existe
logStep "Instalando Space Mono Nerd Font"
if ! [ -d $HOME/.fonts ]; then
  mkdir $HOME/.fonts
fi
cp $DOTFILES/fonts/space-mono-nerd-font-complete-mono.ttf $HOME/.fonts

logStep "Instalando Kitty"
sudo apt -y install kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

logStep "Copiando .bash_aliases"
rm -rf $HOME/.bash_aliases
ln -s $DOTFILES/alias/.bash_aliases $HOME
source $HOME/.bash_aliases

logStep "Configurando Conky"
sudo apt -y install conky
rm -rf $HOME/.conkyrc
rm -rf $HOME/.config/conky
mkdir -p $HOME/.config/conky
ln -s $DOTFILES/conky/.conkyrc $HOME

logStep "Configurando TMUX"
sudo apt -y install tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

logStep "Copiando arquivos do nvim"
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

logStep "Copiando pycodestyle"
rm $HOME/.config/pycodestyle
ln -s $DOTFILES/config/pycodestyle $HOME/.config/pycodestyle

logStep "ZSH"
sudo apt -y install zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
chsh -s $(which zsh)
sudo chsh -s $(which zsh)

logStep "NVM"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash 

logStep "Instalações concluídas"
