#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.bash_aliases
ln -s $DOTFILES/alias/.bash_aliases $HOME

rm -rf $HOME/.vimrc
ln -s $DOTFILES/nvim/.vimrc $HOME

#rm -rf $HOME/.config/nvim/init.vim
#ln -s $DOTFILES/nvim/.vimrc $HOME/.config/nvim/init.vim

rm -rf $HOME/.conkyrc
rm -rf $HOME/.config/conky
ln -s $DOTFILES/conky/.conkyrc $HOME
mkdir -p $HOME/.config/conky

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

